// packages/app/src/app/srs/grade/grade.component.ts
import { Component, EventEmitter, Input, OnInit, Output } from '@angular/core';
import { CardItem, StudyFlowType } from '@vocably/model';
import { craftTheStrategy, ImmediateStep, SrsScore } from '@vocably/srs';
import { CardSfComponent } from '../card-sf/card-sf.component';
import { CardSbComponent } from '../card-sb/card-sb.component';
import { CardMbComponent } from '../card-mb/card-mb.component';
import { CardMfComponent } from '../card-mf/card-mf.component';
import { CardAbComponent } from '../card-ab/card-ab.component';

@Component({
  selector: 'app-srs-grade',
  imports: [
    CardSfComponent,
    CardSbComponent,
    CardMbComponent,
    CardMfComponent,
    CardAbComponent,
  ],
  templateUrl: './grade.component.html',
  styleUrl: './grade.component.scss',
})
export class GradeComponent implements OnInit {
  @Input() allCards!: CardItem[];
  @Input() prerenderedCards!: CardItem[];
  @Input() card!: CardItem;
  @Input() studySteps!: StudyFlowType[];
  @Output() grade = new EventEmitter<SrsScore>();

  step: ImmediateStep;

  ngOnInit(): void {
    this.step = craftTheStrategy({
      studySteps: this.studySteps,
      card: this.card,
      allCards: this.allCards,
      prerenderedCards: this.prerenderedCards,
    }).immediateStep;
  }
}

@switch (step.step) {
  @case ('sf') {
    <app-srs-card-sf
      [card]="card"
      (grade)="grade.emit($event)"
    ></app-srs-card-sf>
  }
  @case ('sb') {
    <app-srs-card-sb
      [card]="card"
      (grade)="grade.emit($event)"
    ></app-srs-card-sb>
  }
  @case ('mf') {
    <app-srs-card-mf
      [card]="card"
      [wrongOptions]="step.multiChoice"
      (grade)="grade.emit($event)"
    ></app-srs-card-mf>
  }
  @case ('mb') {
    <app-srs-card-mb
      [card]="card"
      [wrongOptions]="step.multiChoice"
      (grade)="grade.emit($event)"
    ></app-srs-card-mb>
  }
  @case ('ab') {
    <app-srs-card-ab
      [card]="card"
      (grade)="grade.emit($event)"
    ></app-srs-card-ab>
  }
  @default {
    Unrecognized step.
  }
}

// mobile-app/src/study/Grade.tsx
import { CardItem, StudyFlowType } from '@vocably/model';
import { craftTheStrategy, SrsScore } from '@vocably/srs';
import React, { FC } from 'react';
import { ArrangeByLetters } from './ArrangeByLetters';
import { Card } from './Card';
import { MultiChoice } from './MultiChoice';
import { SwipeGrade } from './SwipeGrade';

type Props = {
  autoPlay: boolean;
  studySteps: StudyFlowType[];
  card: CardItem;
  onGrade: (score: SrsScore) => void;
  existingCards: CardItem[];
  prerenderedCards: CardItem[];
};

export const Grade: FC<Props> = ({
  card,
  studySteps,
  existingCards,
  autoPlay,
  onGrade,
  prerenderedCards,
}) => {
  const { immediateStep } = craftTheStrategy({
    studySteps,
    card,
    allCards: existingCards,
    prerenderedCards,
  });

  const strategyStep = () => {
    switch (immediateStep.step) {
      case 'sb':
        return (
          <SwipeGrade onGrade={onGrade} key={card.id}>
            <Card autoPlay={autoPlay} card={card} direction="back" />
          </SwipeGrade>
        );
      case 'mf':
        return (
          <MultiChoice
            key={card.id}
            autoPlay={autoPlay}
            card={card}
            alternatives={immediateStep.multiChoice}
            onGrade={onGrade}
            direction="front"
          />
        );
      case 'mb':
        return (
          <MultiChoice
            key={card.id}
            autoPlay={autoPlay}
            card={card}
            alternatives={immediateStep.multiChoice}
            onGrade={onGrade}
            direction="back"
          />
        );
      case 'ab':
        return (
          <ArrangeByLetters
            autoPlay={autoPlay}
            key={card.id}
            card={card}
            onGrade={onGrade}
          />
        );
      default:
        return (
          <SwipeGrade onGrade={onGrade} key={card.id}>
            <Card autoPlay={autoPlay} card={card} direction="front" />
          </SwipeGrade>
        );
    }
  };

  return <>{strategyStep()}</>;
};
